--employees 테이블 전체 내용 조회
SELECT
    *
FROM
    employees;
--employees 테이블 first_name, last_name, job_id만 조회
SELECT
    first_name,
    last_name,
    job_id
FROM
    employees;

--사원번호가 176인 사람의 LAST_NAME 조회
SELECT
    last_name
FROM
    employees
WHERE
    employee_id = 176;

--연봉이 12000 이상 되는 직원들의 LAST_NAME,SALARY 조회
SELECT
    last_name,
    salary
FROM
    employees
WHERE
    salary >= 12000;

--연봉이 5000에서 12000 범위가 아닌 사람들의 LAST_NAME, SALARY 조회
SELECT
    last_name,
    salary
FROM
    employees
WHERE
        salary > 12000
    OR salary < 5000 ORDER BY LAST_NAME DESC;
    
--20,50번 부서에서 근무하는 모든 사원들의 LAST_NAME, 부서번호를 오름차순으로 조회
SELECT LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID IN(20,50) ORDER BY lAST_NAME, DEPARTMENT_ID;

--커미션을 받는 모든 사원들의 LAST_NAME, 연봉, 커미션 조회(연봉의 내림차순, 커미션 내림차순)
SELECT LAST_NAME,SALARY,commission_pct FROM EMPLOYEES WHERE COMMISSION_PCT >0 ORDER BY SALARY DESC, commission_pct DESC;

--연봉이 2500,3500,7000이 아니며 직업이 SA_REP나 ST_CLERK인 사원 조회
SELECT * FROM EMPLOYEES WHERE SALARY NOT IN(2500,3500,7000) AND JOB_ID IN('SA_REP','ST_CLERK');

--2008/02/20~2008/05/01 사이에 고용된 사원들의 LAST_NAME,사번,고용일자(내림차순) 조회
--날짜 표현 시 홀따옴표 안에 '-' OR '/' 사용 가능
SELECT LAST_NAME,EMPLOYEE_ID,HIRE_DATE FROM EMPLOYEES WHERE '2008-02-20'<=HIRE_DATE AND HIRE_DATE<='2008-05-01' ORDER BY HIRE_DATE DESC;
SELECT LAST_NAME,EMPLOYEE_ID,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '2008-02-20' AND '2008-05-01' ORDER BY HIRE_DATE DESC;

--2004년도에 고용된 사원들의 LAST_NAME, HIRE_DATE(오름차순) 조회
SELECT LAST_NAME,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE>='2004-01-01' AND HIRE_DATE<='2004-12-31' C
SELECT LAST_NAME,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '2004-01-01' AND '2004-12-31' ORDER BY HIRE_DATE;

--부서가 20,50이고 연봉이 5000~12000 범위인 사람들의 LAST_NAME, SALARY(오름차순) 조회
SELECT LAST_NAME,SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID IN(20,50) AND SALARY BETWEEN 5000 AND 12000 ORDER BY SALARY;

--2004년도에 고용된 사원들의 LAST_NAME, HIRE_DATE(오름차순) 조회 => LIKE를 이용
SELECT LAST_NAME,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE LIKE '04%' ORDER BY HIRE_DATE;

--LAST_NAME에 U가 포함된 사원들의 사번, LAST_NAME 조회
SELECT LAST_NAME,EMPLOYEE_ID FROM EMPLOYEES WHERE LAST_NAME LIKE '%U%';

--LAST_NAME에 네 번째 글자가 A인 사원들의 LAST_NAME 조회
SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '___A%';

--LAST_NAME에 A 혹은 E가 포함된 사원들의 LAST_NAME(오름차순) 조회
SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '%A%' OR LAST_NAME LIKE '%E%' ORDER BY LAST_NAME;

--LAST_NAME에 A와 E가 포함된 사원들의 LAST_NAME(오름차순) 조회
SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '%A%E%' OR LAST_NAME LIKE '%E%A%' ORDER BY LAST_NAME;

--매니저가 없는 사람들의 LAST_NAME,JOB_ID 조회
SELECT LAST_NAME,JOB_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL OR MANAGER_ID='';

--JOB_ID가 ST_CLERK인 사원의 부서번호 조회(단, 부서번호가 NULL인 사원은 제외한다.)
--중복을 제거한 후 부서번호만 조회
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES WHERE JOB_ID='ST_CLERK' AND DEPARTMENT_ID IS NOT NULL;

--COMMISSION_PCT가 NULL이 아닌 사원들 중에서 COMMISSION=SALARY*COMMISSION_PCT를 구하여 EMPLOYEE_ID,FIRST_NAME,JOB_ID 출력
SELECT EMPLOYEE_ID,FIRST_NAME,JOB_ID,SALARY*COMMISSION_PCT as commiSsion FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;