--employees 테이블 전체 내용 조회
SELECT
    *
FROM
    employees;
--employees 테이블 first_name, last_name, job_id만 조회
SELECT
    first_name,
    last_name,
    job_id
FROM
    employees;

--사원번호가 176인 사람의 LAST_NAME 조회
SELECT
    last_name
FROM
    employees
WHERE
    employee_id = 176;

--연봉이 12000 이상 되는 직원들의 LAST_NAME,SALARY 조회
SELECT
    last_name,
    salary
FROM
    employees
WHERE
    salary >= 12000;

--연봉이 5000에서 12000 범위가 아닌 사람들의 LAST_NAME, SALARY 조회
SELECT
    last_name,
    salary
FROM
    employees
WHERE
        salary > 12000
    OR salary < 5000 ORDER BY LAST_NAME DESC;
    
--20,50번 부서에서 근무하는 모든 사원들의 LAST_NAME, 부서번호를 오름차순으로 조회
SELECT LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID IN(20,50) ORDER BY lAST_NAME, DEPARTMENT_ID;

--커미션을 받는 모든 사원들의 LAST_NAME, 연봉, 커미션 조회(연봉의 내림차순, 커미션 내림차순)
SELECT LAST_NAME,SALARY,commission_pct FROM EMPLOYEES WHERE COMMISSION_PCT >0 ORDER BY SALARY DESC, commission_pct DESC;

--연봉이 2500,3500,7000이 아니며 직업이 SA_REP나 ST_CLERK인 사원 조회
SELECT * FROM EMPLOYEES WHERE SALARY NOT IN(2500,3500,7000) AND JOB_ID IN('SA_REP','ST_CLERK');

--2008/02/20~2008/05/01 사이에 고용된 사원들의 LAST_NAME,사번,고용일자(내림차순) 조회
--날짜 표현 시 홀따옴표 안에 '-' OR '/' 사용 가능
SELECT LAST_NAME,EMPLOYEE_ID,HIRE_DATE FROM EMPLOYEES WHERE '2008-02-20'<=HIRE_DATE AND HIRE_DATE<='2008-05-01' ORDER BY HIRE_DATE DESC;
SELECT LAST_NAME,EMPLOYEE_ID,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '2008-02-20' AND '2008-05-01' ORDER BY HIRE_DATE DESC;

--2004년도에 고용된 사원들의 LAST_NAME, HIRE_DATE(오름차순) 조회
SELECT LAST_NAME,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE>='2004-01-01' AND HIRE_DATE<='2004-12-31' C
SELECT LAST_NAME,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '2004-01-01' AND '2004-12-31' ORDER BY HIRE_DATE;

--부서가 20,50이고 연봉이 5000~12000 범위인 사람들의 LAST_NAME, SALARY(오름차순) 조회
SELECT LAST_NAME,SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID IN(20,50) AND SALARY BETWEEN 5000 AND 12000 ORDER BY SALARY;

--2004년도에 고용된 사원들의 LAST_NAME, HIRE_DATE(오름차순) 조회 => LIKE를 이용
SELECT LAST_NAME,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE LIKE '04%' ORDER BY HIRE_DATE;

--LAST_NAME에 U가 포함된 사원들의 사번, LAST_NAME 조회
SELECT LAST_NAME,EMPLOYEE_ID FROM EMPLOYEES WHERE LAST_NAME LIKE '%U%';

--LAST_NAME에 네 번째 글자가 A인 사원들의 LAST_NAME 조회
SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '___A%';

--LAST_NAME에 A 혹은 E가 포함된 사원들의 LAST_NAME(오름차순) 조회
SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '%A%' OR LAST_NAME LIKE '%E%' ORDER BY LAST_NAME;

--LAST_NAME에 A와 E가 포함된 사원들의 LAST_NAME(오름차순) 조회
SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '%A%E%' OR LAST_NAME LIKE '%E%A%' ORDER BY LAST_NAME;

--매니저가 없는 사람들의 LAST_NAME,JOB_ID 조회
SELECT LAST_NAME,JOB_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL OR MANAGER_ID='';

--JOB_ID가 ST_CLERK인 사원의 부서번호 조회(단, 부서번호가 NULL인 사원은 제외한다.)
--중복을 제거한 후 부서번호만 조회
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES WHERE JOB_ID='ST_CLERK' AND DEPARTMENT_ID IS NOT NULL;

--COMMISSION_PCT가 NULL이 아닌 사원들 중에서 COMMISSION=SALARY*COMMISSION_PCT를 구하여 EMPLOYEE_ID,FIRST_NAME,JOB_ID 출력
SELECT EMPLOYEE_ID,FIRST_NAME,JOB_ID,SALARY*COMMISSION_PCT as commiSsion FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;

--2023.03.21--
--FIRST_NAME이 CURTIS인 사람의 FIRST_NAME,EMAIL,PHONE_NUMBER,JOB_ID를 조회한다.
--단, JOB_ID의 결과는 소문자로 출력되도록 한다.
SELECT FIRST_NAME,EMAIL,PHONE_NUMBER,LOWER(JOB_ID) FROM EMPLOYEES WHERE FIRST_NAME='CURTIS';

--부서번호가 60,70,80,90인 사원들의 EMPLOYEE_ID,FIRST_NAME,HIRE_DATE,JOB_ID 조회
--단, JOB_ID가 IT_PROG인 사원의 경우 프로그래머로 변경한 후 출력
SELECT EMPLOYEE_ID,FIRST_NAME,HIRE_DATE,REPLACE(JOB_ID,'IT_PROG','프로그래머') 
FROM EMPLOYEES WHERE DEPARTMENT_ID IN(60,70,80,90);

--JOB_ID가 AD_PRES,PU_CLERK인 사원들의 EMPLOYEE_ID,FIRST_NAME,LAST_NAME,DEARTMENT_ID,JOB_ID를 조회한다.
--단, 사원명은 FIRST_NAME과 LAST_NAME을 연결하여 출력하시오.
SELECT EMPLOYEE_ID,CONCAT(FIRST_NAME,CONCAT(' ',LAST_NAME)),DEPARTMENT_ID,JOB_ID 
FROM EMPLOYEES WHERE JOB_ID IN('AD_PRES','PU_CLERK');

SELECT EMPLOYEE_ID,FIRST_NAME||' '||LAST_NAME,DEPARTMENT_ID,JOB_ID
FROM EMPLOYEES WHERE JOB_ID IN('AD_PRES','PU_CLERK');


--[실습]
SELECT LAST_NAME,SALARY,
CASE WHEN SALARY BETWEEN 0 AND 1999 THEN 0.00
WHEN SALARY BETWEEN 2000 AND 3999 THEN 0.09
WHEN SALARY BETWEEN 4000 AND 5999 THEN 0.20
WHEN SALARY BETWEEN 6000 AND 7999 THEN 0.30
WHEN SALARY BETWEEN 8000 AND 9999 THEN 0.40
WHEN SALARY BETWEEN 10000 AND 11999 THEN 0.42
WHEN SALARY BETWEEN 12000 AND 13999 THEN 0.44
ELSE 0.45
END AS TAX_RATE 
FROM EMPLOYEES WHERE DEPARTMENT_ID=80;
--선생님 버전
SELECT LAST_NAME,SALARY,
DECODE(TRUNC(SALARY/2000,0),0,0.00,1,0.09,2,0.20,3,0.30,4,0.40,5,0.42,6,0.44,0.45) AS TAX_RATE 
FROM EMPLOYEES WHERE DEPARTMENT_ID=80;


--회사 내의 최대 연봉 및 최소 연봉의 차이를 출력
SELECT MAX(SALARY)-MIN(SALARY) AS SAL_GAP FROM EMPLOYEES;

--매니저로 근무하는 사원들의 총 숫자 출력(매니저 중복 제거)
SELECT COUNT(DISTINCT MANAGER_ID) FROM EMPLOYEES;


--2023.03.22--
--[실습1]
--JOIN
--##1##
--자신의 담당 매니저의 고용일보다 빠른 입사자 찾기(SELF JOIN, EMPLOYEES)
--HIRE_DATE, LAST_NAME, MANAGER_ID 조회
SELECT E1.HIRE_DATE, E1.LAST_NAME, E1.MANAGER_ID
FROM EMPLOYEES E1,EMPLOYEES E2 
WHERE E2.EMPLOYEE_ID=E1.MANAGER_ID AND E1.HIRE_DATE<E2.HIRE_DATE;

--##2##
--도시 이름이 T로 시작하는 지역에 사는 사원들의 사번, LAST_NAME, 부서번호, 도시 조회
--EMPLOYEES, DEPARTMENTS,LOCATIONS,INNER JOIN
SELECT E.EMPLOYEE_ID,E.LAST_NAME,D.DEPARTMENT_ID,L.CITY FROM EMPLOYEES E,DEPARTMENTS D,LOCATIONS L
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID AND D.LOCATION_ID=L.LOCATION_ID AND L.CITY LIKE 'T%';

--##3##
--위치 ID가 1700인 사원들의 사번, LAST_NAME, 부서번호, 급여 조회
--EMPLOYEES, DEPARTMENTS, INNER JOIN
SELECT E.EMPLOYEE_ID,E.LAST_NAME,D.DEPARTMENT_ID,E.SALARY FROM EMPLOYEES E,DEPARTMENTS D
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID AND D.LOCATION_ID=1700;

--##4##
--부서명, 위치ID, 각 부서별 사원 총 수, 각 부서별 평균 연봉 조회
--평균 연봉은 소수점 2자리까지만
--EMPLOYEES, DEPARTMENTS, INNER JOIN
SELECT D.DEPARTMENT_NAME,D.LOCATION_ID,COUNT(E.EMPLOYEE_ID),TRUNC(AVG(E.SALARY),2) AS AVG_SALARY
FROM EMPLOYEES E,DEPARTMENTS D
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME,D.LOCATION_ID;

--##5##
--EXECUTIVE 부서에 근무하는 사원들의 부서번호, LAST_NAME, JOB_ID 조회
--EMPLOYEES, DEPARTMENTS, INNER JOIN
SELECT D.DEPARTMENT_ID,E.LAST_NAME,E.JOB_ID
FROM EMPLOYEES E,DEPARTMENTS D
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID AND D.DEPARTMENT_NAME='Executive';

--##6##
--각 사원별 소속 부서에서 자신보다 늦게 고용되었으나 보다 많은 연봉을 받는 사원이 존재하는 모든 사원들의
--부서번호, 이름(FIRST_NAME과 LAST_NAME 연결하기), SALARY, HIRE_DATE 조회
--EMPLOYEES, SELF JOIN
SELECT DISTINCT E1.DEPARTMENT_ID,E1.FIRST_NAME||' '||E1.LAST_NAME AS NAME, E1.SALARY, E1.HIRE_DATE
FROM EMPLOYEES E1,EMPLOYEES E2
WHERE E2.DEPARTMENT_ID=E1.DEPARTMENT_ID AND E1.HIRE_DATE<E2.HIRE_DATE AND E1.SALARY<E2.SALARY;


--[실습2]
--서브쿼리, 조인
--##1##
--LAST_NAME에 U가 포함된 사원들과 동일 부서에 근무하는 사원들의 사번, LAST_NAME 조회
SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME LIKE '%U%');

--##2##
--JOB_ID가 SA_MAN인 사원들의 최대 연봉보다 높게 받는 사원들의 LAST_NAME, JOB_ID, SALARY 조회
SELECT LAST_NAME, JOB_ID, SALARY FROM EMPLOYEES
WHERE SALARY > (SELECT MAX(SALARY) FROM EMPLOYEES WHERE JOB_ID='SA_MAN');

--##3##
--커미션을 버는 사원들의 부서와 연봉이 동일한 사원들의 LAST_NAME, DEPARTMENT_ID, SALARY 조회
SELECT LAST_NAME, DEPARTMENT_ID, SALARY FROM EMPLOYEES
WHERE SALARY*12 IN(SELECT SALARY*12 FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL);

--##4##
--회사 전체 평균 연봉보다 더 받는 사원들 중 LAST_NAME에 U가 있는 사원들이 근무하는 부서에서 근무하는 사원들의 EMPLOYEE_ID, LAST_NAME, SALARY 조회
SELECT EMPLOYEE_ID, LAST_NAME, SALARY FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME LIKE '%U%') 
AND SALARY*12 > (SELECT AVG(SALARY*12) FROM EMPLOYEES);

--##5##
--LAST_NAME이 DAVIES인 사람보다 나중에 고용된 사원들의 LAST_NAME, HIRE_DATE 조회
SELECT LAST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE > (SELECT HIRE_DATE FROM EMPLOYEES WHERE LAST_NAME='DAVIES');

--##6##
--LAST_NAME이 KING인 사원을 매니저로 두고 있는 모든 사원들의 LAST_NAME, SALARY 조회

