--<JAVADB>--

--1. USERTBL 테이블 생성
--NO: 숫자 4자리, USERNAME: 한글 4자리, BIRTHYEAR: 년도 숫자 4자리, ADDR: 주소 한글/숫자, MOBILE: 010-1234-1234
--NO PK 제약조건 지정(제약조건명: PK_USERTBL)
CREATE TABLE USERTBL(
NO NUMBER(4) CONSTRAINT PK_USERTBL PRIMARY KEY,
USERNAME NVARCHAR2(4) NOT NULL,
BIRTHYEAR NUMBER(4) NOT NULL,
ADDR VARCHAR2(50) NOT NULL,
MOBILE VARCHAR2(50));

--시퀀스 생성
--USER_SEQ 생성(기본)
CREATE SEQUENCE USER_SEQ;

--행 추가
INSERT INTO USERTBL(NO, USERNAME, BIRTHYEAR, ADDR, MOBILE) 
VALUES(USER_SEQ.NEXTVAL, '홍길동', 1990, '서울시 서초구 서초중앙로200', '010-1234-1234');

COMMIT;


--모든 컬럼은 NOT NULL
--2. PAYTYPE 테이블 생성
--PAYTYPE: PAY_NO(숫자 1자리-PK), INFO(영어 4자리)
--PAYTYPE_SEQ 생성
CREATE TABLE PAYTYPE(
PAY_NO NUMBER(1) PRIMARY KEY,
INFO VARCHAR2(4) NOT NULL);

CREATE SEQUENCE PAYTYPE_SEQ;

INSERT INTO PAYTYPE VALUES(PAYTYPE_SEQ.NEXTVAL, 'CARD');
INSERT INTO PAYTYPE VALUES(PAYTYPE_SEQ.NEXTVAL, 'CASH');

SELECT * FROM PAYTYPE; --1: CARD, 2: CASH 


--3. SHOP USER 테이블 생성
--SUSER: USER_ID(숫자 4자리-PK), NAME(한글), PAY_NO(숫자 1자리: PAYTYPE에 있는 PAY_NO 참조해서 사용)
CREATE TABLE SUSER(
USER_ID NUMBER(4) PRIMARY KEY,
NAME VARCHAR2(50) NOT NULL,
PAY_NO NUMBER(1) NOT NULL CONSTRAINT SUSER_PAY_NO_FK REFERENCES PAYTYPE(PAY_NO));


--4. PRODUCT 테이블 생성
--PRODUCT: PRODUCT_ID(숫자 8자리-PK), PNAME(문자), PRICE(숫자), CONTENT(문자 FOR 해상도)
CREATE TABLE PRODUCT(
PRODUCT_ID NUMBER(8) PRIMARY KEY,
PNAME VARCHAR2(50) NOT NULL,
PRICE NUMBER(10) NOT NULL,
CONTENT VARCHAR2(50) NOT NULL);


--5. SHOP ORDER 테이블 생성
--SORDER: ORDER_ID(숫자 8자리-PK), USER_ID(USER에 있는 USER_ID 참조), PRODUCT_ID(PRODUCT에 있는 PRODUCT_ID 참조)
--ORDER_SEQ 생성
CREATE TABLE SORDER(
ORDER_ID NUMBER(8) PRIMARY KEY,
USER_ID NOT NULL CONSTRAINT SORDER_USER_ID_FK REFERENCES SUSER(USER_ID),
PRODUCT_ID NOT NULL CONSTRAINT SORDER_PRODUCT_ID_FK REFERENCES PRODUCT(PRODUCT_ID));
--구매일 추가
ALTER TABLE SORDER ADD ORDER_DATE DATE;

CREATE SEQUENCE ORDER_SEQ;
--장바구니
--INSERT INTO SORDER VALUES(ORDER_SEQ.NEXTVAL, 물건을 구매한 ID, 상품ID, SYODATE)
--주문 정보 전체 조회
SELECT * FROM SORDER;


--6. SUSER와 PAYTYPE 조인
SELECT S.USER_ID, S.NAME, P.PAY_NO, P.INFO FROM SUSER S, PAYTYPE P 
WHERE S.PAY_NO=P.PAY_NO AND S.USER_ID=1000;


--7. 전체 주문 목록 조회: 기준은 SORDER
--USER_ID, NAME, CARD/CASH, PRODUCT_ID, PNAME, PRICE, CONTENT
--SUSER 테이블: NAME, PAYTYPE 테이블: CARD/CASH, PRODUCT 테이블: PRODUCT_ID, PNAME, PRICE, CONTENT
SELECT O.USER_ID, S.NAME, T.INFO, P.PRODUCT_ID, P.PNAME, P.PRICE, P.CONTENT, O.ORDER_DATE
FROM SORDER O, SUSER S, PAYTYPE T, PRODUCT P 
WHERE O.USER_ID=S.USER_ID AND O.PRODUCT_ID=P.PRODUCT_ID AND S.PAY_NO=T.PAY_NO;


--8. 홍길동 주문 목록 조회: 기준은 SORDER
--USER_ID, NAME, CARD/CASH, PRODUCT_ID, PNAME, PRICE, CONTENT
--SUSER 테이블: NAME, PAYTYPE 테이블: CARD/CASH, PRODUCT 테이블: PRODUCT_ID, PNAME, PRICE, CONTENT
SELECT O.USER_ID, S.NAME, T.INFO, P.PRODUCT_ID, P.PNAME, P.PRICE, P.CONTENT, O.ORDER_DATE
FROM SORDER O, SUSER S, PAYTYPE T, PRODUCT P 
WHERE O.USER_ID=S.USER_ID AND O.PRODUCT_ID=P.PRODUCT_ID AND S.PAY_NO=T.PAY_NO AND O.USER_ID=1000;





