--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-23-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "JAVADB"."BOARD" 
   (	"BNO" NUMBER(8,0), 
	"NAME" NVARCHAR2(10), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"TITLE" NVARCHAR2(50), 
	"CONTENT" NVARCHAR2(1000), 
	"ATTACH" NVARCHAR2(100), 
	"RE_REF" NUMBER(8,0), 
	"RE_LEV" NUMBER(8,0), 
	"RE_SEQ" NUMBER(8,0), 
	"CNT" NUMBER(8,0) DEFAULT 0, 
	"REGDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVADB"."PK_BOARD" ON "JAVADB"."BOARD" ("BNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "JAVADB"."BOARD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."BOARD" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."BOARD" MODIFY ("RE_REF" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."BOARD" MODIFY ("RE_LEV" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."BOARD" MODIFY ("RE_SEQ" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY ("BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
