--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-23-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOKTBL
--------------------------------------------------------

  CREATE TABLE "JAVADB"."BOOKTBL" 
   (	"CODE" NUMBER(4,0), 
	"TITLE" NVARCHAR2(20), 
	"WRITER" NVARCHAR2(20), 
	"PRICE" NUMBER(8,0), 
	"DESCRIPTION" NVARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008416
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVADB"."SYS_C008416" ON "JAVADB"."BOOKTBL" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOOKTBL
--------------------------------------------------------

  ALTER TABLE "JAVADB"."BOOKTBL" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."BOOKTBL" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."BOOKTBL" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."BOOKTBL" ADD PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
