--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-23-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBERTBL
--------------------------------------------------------

  CREATE TABLE "JAVADB"."MEMBERTBL" 
   (	"USERID" VARCHAR2(15 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"NAME" NVARCHAR2(10), 
	"GENDER" NVARCHAR2(2), 
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008421
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVADB"."SYS_C008421" ON "JAVADB"."MEMBERTBL" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBERTBL
--------------------------------------------------------

  ALTER TABLE "JAVADB"."MEMBERTBL" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."MEMBERTBL" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."MEMBERTBL" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."MEMBERTBL" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."MEMBERTBL" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
