--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-23-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SORDER
--------------------------------------------------------

  CREATE TABLE "JAVADB"."SORDER" 
   (	"ORDER_ID" NUMBER(8,0), 
	"USER_ID" NUMBER(4,0), 
	"PRODUCT_ID" NUMBER(8,0), 
	"ORDER_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008409
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVADB"."SYS_C008409" ON "JAVADB"."SORDER" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SORDER
--------------------------------------------------------

  ALTER TABLE "JAVADB"."SORDER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."SORDER" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."SORDER" ADD PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SORDER
--------------------------------------------------------

  ALTER TABLE "JAVADB"."SORDER" ADD CONSTRAINT "SORDER_USER_ID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "JAVADB"."SUSER" ("USER_ID") ENABLE;
  ALTER TABLE "JAVADB"."SORDER" ADD CONSTRAINT "SORDER_PRODUCT_ID_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "JAVADB"."PRODUCT" ("PRODUCT_ID") ENABLE;
