--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-23-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SPRING_BOARD
--------------------------------------------------------

  CREATE TABLE "JAVADB"."SPRING_BOARD" 
   (	"BNO" NUMBER(10,0), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"WRITER" VARCHAR2(50 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"UPDATEDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SPRING_BOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVADB"."PK_SPRING_BOARD" ON "JAVADB"."SPRING_BOARD" ("BNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SPRING_BOARD
--------------------------------------------------------

  ALTER TABLE "JAVADB"."SPRING_BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."SPRING_BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."SPRING_BOARD" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."SPRING_BOARD" ADD CONSTRAINT "PK_SPRING_BOARD" PRIMARY KEY ("BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
