--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-23-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUSER
--------------------------------------------------------

  CREATE TABLE "JAVADB"."SUSER" 
   (	"USER_ID" NUMBER(4,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"PAY_NO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008401
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVADB"."SYS_C008401" ON "JAVADB"."SUSER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SUSER
--------------------------------------------------------

  ALTER TABLE "JAVADB"."SUSER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."SUSER" MODIFY ("PAY_NO" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."SUSER" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUSER
--------------------------------------------------------

  ALTER TABLE "JAVADB"."SUSER" ADD CONSTRAINT "SUSER_PAY_NO_FK" FOREIGN KEY ("PAY_NO")
	  REFERENCES "JAVADB"."PAYTYPE" ("PAY_NO") ENABLE;
