--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-23-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERTBL
--------------------------------------------------------

  CREATE TABLE "JAVADB"."USERTBL" 
   (	"NO" NUMBER(4,0), 
	"USERNAME" NVARCHAR2(10), 
	"BIRTHYEAR" NUMBER(4,0), 
	"ADDR" VARCHAR2(50 BYTE), 
	"MOBILE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USERTBL
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVADB"."PK_USERTBL" ON "JAVADB"."USERTBL" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERTBL
--------------------------------------------------------

  ALTER TABLE "JAVADB"."USERTBL" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."USERTBL" MODIFY ("BIRTHYEAR" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."USERTBL" MODIFY ("ADDR" NOT NULL ENABLE);
  ALTER TABLE "JAVADB"."USERTBL" ADD CONSTRAINT "PK_USERTBL" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
